services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/var/lib/kafka/data

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"

  orderingservice:
    build:
      context: ./backend/src/FoodOrdering.OrderingService/FoodOrdering.OrderingService.Api
    ports:
      - "5001:80"
    depends_on:
      - mongo
      - kafka
      - redis

  paymentservice:
    build:
      context: ./backend/src/FoodOrdering.PaymentService/FoodOrdering.PaymentService.Api
    ports:
      - "5002:80"
    depends_on:
      - mongo
      - kafka

  notificationservice:
    build:
      context: ./backend/src/FoodOrdering.NotificationService/FoodOrdering.NotificationService.Api
    ports:
      - "5003:80"
    depends_on:
      - kafka
      - redis

volumes:
  mongo-data:
  zookeeper-data:
  zookeeper-log:
  kafka-data:
